# Generated by Django 4.1.7 on 2023-03-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=8, null=True)),
                ('matricula', models.CharField(blank=True, max_length=8, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id_professor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=8, null=True)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.OneToOneField(db_column='id_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.professores')),
                ('id_professor', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=7, null=True)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
                ('ementa', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Disciplinaaluno',
            fields=[
                ('id_matricula', models.OneToOneField(db_column='id_matricula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.disciplinas')),
                ('id_aluno', models.IntegerField(blank=True, null=True)),
                ('id_disciplina', models.IntegerField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DisciplinaAluno',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.OneToOneField(db_column='id_frequencia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.disciplinas')),
                ('id_materia', models.IntegerField(blank=True, null=True)),
                ('dia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Frequencia',
            },
        ),
        migrations.CreateModel(
            name='Planoaula',
            fields=[
                ('id_plano_aula', models.OneToOneField(db_column='id_plano_aula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.disciplinas')),
                ('id_disciplina', models.IntegerField(blank=True, null=True)),
                ('tema_aula', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo', models.BinaryField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('dia', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PlanoAula',
            },
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id_atividade', models.OneToOneField(db_column='id_atividade', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.planoaula')),
                ('atividade', models.BinaryField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_postagem', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('id_disciplina', models.IntegerField(blank=True, null=True)),
                ('id_plano_aula', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Frequenciaaluno',
            fields=[
                ('id_aluno', models.IntegerField(primary_key=True, serialize=False)),
                ('id_frequencia', models.IntegerField(blank=True, null=True)),
                ('presenca', models.CharField(blank=True, max_length=1, null=True)),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.frequencia')),
            ],
            options={
                'db_table': 'FrequenciaAluno',
            },
        ),
        migrations.CreateModel(
            name='Atividadealuno',
            fields=[
                ('id_atividade', models.IntegerField(primary_key=True, serialize=False)),
                ('id_aluno', models.IntegerField(blank=True, null=True)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.atividades')),
            ],
            options={
                'db_table': 'AtividadeAluno',
            },
        ),
    ]
